const students_data = [
  {
    id: 1,
    name: "Zahirul islam",
    roll: 1,
    class: 5,
    subjects: {
      bangla: 70,
      english: 86,
      math: 74,
      science: 88,
      religion: 90,
      social: 67,
    },
  },
  {
    id: 2,
    name: "Islam rakib",
    roll: 2,
    class: 5,
    subjects: {
      bangla: 71,
      english: 76,
      math: 68,
      science: 73,
      religion: 81,
      social: 73,
    },
  },
  {
    id: 3,
    name: "Masud",
    roll: 3,
    class: 5,
    subjects: {
      bangla: 66,
      english: 74,
      math: 54,
      science: 77,
      religion: 84,
      social: 79,
    },
  },
  {
    id: 4,
    name: "Mukul",
    roll: 4,
    class: 5,
    subjects: {
      bangla: 42,
      english: 55,
      math: 89,
      science: 69,
      religion: 73,
      social: 79,
    },
  },
  {
    id: 5,
    name: "Ismail",
    roll: 5,
    class: 5,
    subjects: {
      bangla: 73,
      english: 81,
      math: 64,
      science: 59,
      religion: 78,
      social: 61,
    },
  },
  {
    id: 6,
    name: "Promis",
    roll: 6,
    class: 5,
    subjects: {
      bangla: 69,
      english: 75,
      math: 64,
      science: 71,
      religion: 91,
      social: 76,
    },
  },
  {
    id: 7,
    name: "Ekram",
    roll: 7,
    class: 5,
    subjects: {
      bangla: 61,
      english: 50,
      math: 31,
      science: 47,
      religion: 67,
      social: 61,
    },
  },
  {
    id: 8,
    name: "Sakib",
    roll: 8,
    class: 5,
    subjects: {
      bangla: 84,
      english: 73,
      math: 91,
      science: 74,
      religion: 68,
      social: 49,
    },
  },
  {
    id: 9,
    name: "Imran",
    roll: 9,
    class: 5,
    subjects: {
      bangla: 74,
      english: 91,
      math: 54,
      science: 49,
      religion: 71,
      social: 68,
    },
  },
  {
    id: 10,
    name: "Sojib",
    roll: 10,
    class: 5,
    subjects: {
      bangla: 89,
      english: 81,
      math: 75,
      science: 69,
      religion: 79,
      social: 72,
    },
  },
];
